@startuml
actor Aluno
participant AuthService as Auth
participant Sistema
participant Biblio as "Bibliotecário"
participant Emp as "Emp"
participant LivroObj as "Livro"

Aluno -> Auth: autenticar(creds)
Auth --> Aluno: retorna Usuario
Aluno -> Sistema: solicitarEmprestimo(livroId)
activate Sistema
Sistema -> Emp: verificarLimite(usuario)
Emp --> Sistema: limiteOK
alt livro indisponível
    Sistema -> Aluno: erro("Livro não disponível")
else OK
    Sistema -> Biblio: aprovarEmpréstimo(details)
    Biblio --> Sistema: aprova | nega
    alt aprovado
        Sistema -> LivroObj: atualizarEstado("Emprestado")
        Sistema -> Emp: registrar(dataEmp, dataPrev)
        Sistema -> Aluno: confirmação
    else negado
        Sistema -> Aluno: notificarNegação()
    end
end
deactivate Sistema
@enduml